{!! Html::script('assets/js/jquery/jquery-2.1.4.js') !!}
{!! Html::script('assets/js/bootstrap/bootstrap.min.js') !!}
{!! Html::script('assets/js/compartidos/jquery.easing.min.js') !!}
{!! Html::script('assets/js/jquery/jqBootstrapValidation.js') !!}
{!! Html::script('assets/page/js/jquery-migrate-1.2.1.js') !!}
{!! Html::script('assets/page/js/jquery.cookie.js') !!}
{!! Html::script('assets/page/js/TMForm.js') !!}
{!! Html::script('assets/page/js/modal.js') !!}
{!! Html::script('assets/page/js/device.min.js') !!}
{!! Html::script('assets/page/js/tmstickup.js') !!}
{!! Html::script('assets/page/js/jquery.easing.1.3.js') !!}
{!! Html::script('assets/page/js/jquery.ui.totop.js') !!}
{!! Html::script('assets/page/js/jquery.mousewheel.min.js') !!}
{!! Html::script('assets/page/js/jquery.simplr.smoothscroll.min.js') !!}
{!! Html::script('assets/page/js/superfish.js') !!}
{!! Html::script('assets/page/js/jquery.mobilemenu.js') !!}
{!! Html::script('assets/page/js/camera.js') !!}
{!! Html::script('assets/page/js/owl.carousel.js') !!}
{!! Html::script('assets/page/js/jquery.stellar.js') !!}
{!! Html::script('assets/page/js/script.js') !!}
{!! Html::script('assets/page/js/jquery.mobile.customized.min.js') !!}
{!! Html::script('assets/page/js/wow.js') !!}
{!! Html::script('assets/page/js/page.js') !!}
{!! Html::script('assets/Slides-SlidesJS-3/source/jquery.slides.js') !!}
