//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCharp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class apicharpEntities : DbContext
    {
        public apicharpEntities()
            : base("name=apicharpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<airplane> airplane { get; set; }
        public virtual DbSet<destination> destination { get; set; }
        public virtual DbSet<pilot> pilot { get; set; }
        public virtual DbSet<Programming> Programming { get; set; }
    }
}
