//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanos.PlanillaServico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Planilla", Namespace="http://schemas.datacontract.org/2004/07/WsRecursosHumanos.Estructuras")]
    [System.SerializableAttribute()]
    public partial class Planilla : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlanillaEmpleado", Namespace="http://schemas.datacontract.org/2004/07/WsRecursosHumanos.Estructuras")]
    [System.SerializableAttribute()]
    public partial class PlanillaEmpleado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDempleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDplanillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double saldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDempleado {
            get {
                return this.IDempleadoField;
            }
            set {
                if ((this.IDempleadoField.Equals(value) != true)) {
                    this.IDempleadoField = value;
                    this.RaisePropertyChanged("IDempleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDplanilla {
            get {
                return this.IDplanillaField;
            }
            set {
                if ((this.IDplanillaField.Equals(value) != true)) {
                    this.IDplanillaField = value;
                    this.RaisePropertyChanged("IDplanilla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double saldo {
            get {
                return this.saldoField;
            }
            set {
                if ((this.saldoField.Equals(value) != true)) {
                    this.saldoField = value;
                    this.RaisePropertyChanged("saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlanillaServico.IPlanilla")]
    public interface IPlanilla {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanilla/AgregarPlanilla", ReplyAction="http://tempuri.org/IPlanilla/AgregarPlanillaResponse")]
        string AgregarPlanilla(RecursosHumanos.PlanillaServico.Planilla planilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanilla/AgregarPlanilla", ReplyAction="http://tempuri.org/IPlanilla/AgregarPlanillaResponse")]
        System.Threading.Tasks.Task<string> AgregarPlanillaAsync(RecursosHumanos.PlanillaServico.Planilla planilla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanilla/EditarPlanilla", ReplyAction="http://tempuri.org/IPlanilla/EditarPlanillaResponse")]
        string EditarPlanilla(RecursosHumanos.PlanillaServico.Planilla planilla, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanilla/EditarPlanilla", ReplyAction="http://tempuri.org/IPlanilla/EditarPlanillaResponse")]
        System.Threading.Tasks.Task<string> EditarPlanillaAsync(RecursosHumanos.PlanillaServico.Planilla planilla, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanilla/TraerPlanillas", ReplyAction="http://tempuri.org/IPlanilla/TraerPlanillasResponse")]
        RecursosHumanos.PlanillaServico.Planilla[] TraerPlanillas(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanilla/TraerPlanillas", ReplyAction="http://tempuri.org/IPlanilla/TraerPlanillasResponse")]
        System.Threading.Tasks.Task<RecursosHumanos.PlanillaServico.Planilla[]> TraerPlanillasAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanilla/ObtenerPlanilla", ReplyAction="http://tempuri.org/IPlanilla/ObtenerPlanillaResponse")]
        RecursosHumanos.PlanillaServico.Planilla ObtenerPlanilla(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanilla/ObtenerPlanilla", ReplyAction="http://tempuri.org/IPlanilla/ObtenerPlanillaResponse")]
        System.Threading.Tasks.Task<RecursosHumanos.PlanillaServico.Planilla> ObtenerPlanillaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanilla/InsertarPlanillaEmpleado", ReplyAction="http://tempuri.org/IPlanilla/InsertarPlanillaEmpleadoResponse")]
        string InsertarPlanillaEmpleado(RecursosHumanos.PlanillaServico.PlanillaEmpleado[] planillaempleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlanilla/InsertarPlanillaEmpleado", ReplyAction="http://tempuri.org/IPlanilla/InsertarPlanillaEmpleadoResponse")]
        System.Threading.Tasks.Task<string> InsertarPlanillaEmpleadoAsync(RecursosHumanos.PlanillaServico.PlanillaEmpleado[] planillaempleado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlanillaChannel : RecursosHumanos.PlanillaServico.IPlanilla, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlanillaClient : System.ServiceModel.ClientBase<RecursosHumanos.PlanillaServico.IPlanilla>, RecursosHumanos.PlanillaServico.IPlanilla {
        
        public PlanillaClient() {
        }
        
        public PlanillaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlanillaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlanillaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlanillaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AgregarPlanilla(RecursosHumanos.PlanillaServico.Planilla planilla) {
            return base.Channel.AgregarPlanilla(planilla);
        }
        
        public System.Threading.Tasks.Task<string> AgregarPlanillaAsync(RecursosHumanos.PlanillaServico.Planilla planilla) {
            return base.Channel.AgregarPlanillaAsync(planilla);
        }
        
        public string EditarPlanilla(RecursosHumanos.PlanillaServico.Planilla planilla, int id) {
            return base.Channel.EditarPlanilla(planilla, id);
        }
        
        public System.Threading.Tasks.Task<string> EditarPlanillaAsync(RecursosHumanos.PlanillaServico.Planilla planilla, int id) {
            return base.Channel.EditarPlanillaAsync(planilla, id);
        }
        
        public RecursosHumanos.PlanillaServico.Planilla[] TraerPlanillas(string filtro) {
            return base.Channel.TraerPlanillas(filtro);
        }
        
        public System.Threading.Tasks.Task<RecursosHumanos.PlanillaServico.Planilla[]> TraerPlanillasAsync(string filtro) {
            return base.Channel.TraerPlanillasAsync(filtro);
        }
        
        public RecursosHumanos.PlanillaServico.Planilla ObtenerPlanilla(int id) {
            return base.Channel.ObtenerPlanilla(id);
        }
        
        public System.Threading.Tasks.Task<RecursosHumanos.PlanillaServico.Planilla> ObtenerPlanillaAsync(int id) {
            return base.Channel.ObtenerPlanillaAsync(id);
        }
        
        public string InsertarPlanillaEmpleado(RecursosHumanos.PlanillaServico.PlanillaEmpleado[] planillaempleado) {
            return base.Channel.InsertarPlanillaEmpleado(planillaempleado);
        }
        
        public System.Threading.Tasks.Task<string> InsertarPlanillaEmpleadoAsync(RecursosHumanos.PlanillaServico.PlanillaEmpleado[] planillaempleado) {
            return base.Channel.InsertarPlanillaEmpleadoAsync(planillaempleado);
        }
    }
}
