//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanos.AulaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adminstrador", Namespace="http://schemas.datacontract.org/2004/07/WebServiceProyectoUniversidad.Estructuras" +
        "")]
    [System.SerializableAttribute()]
    public partial class Adminstrador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aula", Namespace="http://schemas.datacontract.org/2004/07/WebServiceProyectoUniversidad.Estructuras" +
        "")]
    [System.SerializableAttribute()]
    public partial class Aula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_AulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_AulaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Aula {
            get {
                return this.ID_AulaField;
            }
            set {
                if ((this.ID_AulaField.Equals(value) != true)) {
                    this.ID_AulaField = value;
                    this.RaisePropertyChanged("ID_Aula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Aula {
            get {
                return this.Nombre_AulaField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_AulaField, value) != true)) {
                    this.Nombre_AulaField = value;
                    this.RaisePropertyChanged("Nombre_Aula");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AulaService.IAulaService")]
    public interface IAulaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAulaService/InsertarAula", ReplyAction="http://tempuri.org/IAulaService/InsertarAulaResponse")]
        string InsertarAula(string nombre, RecursosHumanos.AulaService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAulaService/InsertarAula", ReplyAction="http://tempuri.org/IAulaService/InsertarAulaResponse")]
        System.Threading.Tasks.Task<string> InsertarAulaAsync(string nombre, RecursosHumanos.AulaService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAulaService/ModificarAula", ReplyAction="http://tempuri.org/IAulaService/ModificarAulaResponse")]
        string ModificarAula(RecursosHumanos.AulaService.Aula aula, RecursosHumanos.AulaService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAulaService/ModificarAula", ReplyAction="http://tempuri.org/IAulaService/ModificarAulaResponse")]
        System.Threading.Tasks.Task<string> ModificarAulaAsync(RecursosHumanos.AulaService.Aula aula, RecursosHumanos.AulaService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAulaService/EliminarAula", ReplyAction="http://tempuri.org/IAulaService/EliminarAulaResponse")]
        string EliminarAula(int ID_Aula, RecursosHumanos.AulaService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAulaService/EliminarAula", ReplyAction="http://tempuri.org/IAulaService/EliminarAulaResponse")]
        System.Threading.Tasks.Task<string> EliminarAulaAsync(int ID_Aula, RecursosHumanos.AulaService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAulaService/TraerAulas", ReplyAction="http://tempuri.org/IAulaService/TraerAulasResponse")]
        RecursosHumanos.AulaService.Aula[] TraerAulas(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAulaService/TraerAulas", ReplyAction="http://tempuri.org/IAulaService/TraerAulasResponse")]
        System.Threading.Tasks.Task<RecursosHumanos.AulaService.Aula[]> TraerAulasAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAulaService/ObtenerAula", ReplyAction="http://tempuri.org/IAulaService/ObtenerAulaResponse")]
        RecursosHumanos.AulaService.Aula ObtenerAula(int ID_Aula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAulaService/ObtenerAula", ReplyAction="http://tempuri.org/IAulaService/ObtenerAulaResponse")]
        System.Threading.Tasks.Task<RecursosHumanos.AulaService.Aula> ObtenerAulaAsync(int ID_Aula);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAulaServiceChannel : RecursosHumanos.AulaService.IAulaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AulaServiceClient : System.ServiceModel.ClientBase<RecursosHumanos.AulaService.IAulaService>, RecursosHumanos.AulaService.IAulaService {
        
        public AulaServiceClient() {
        }
        
        public AulaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AulaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AulaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AulaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertarAula(string nombre, RecursosHumanos.AulaService.Adminstrador administrador) {
            return base.Channel.InsertarAula(nombre, administrador);
        }
        
        public System.Threading.Tasks.Task<string> InsertarAulaAsync(string nombre, RecursosHumanos.AulaService.Adminstrador administrador) {
            return base.Channel.InsertarAulaAsync(nombre, administrador);
        }
        
        public string ModificarAula(RecursosHumanos.AulaService.Aula aula, RecursosHumanos.AulaService.Adminstrador administrador) {
            return base.Channel.ModificarAula(aula, administrador);
        }
        
        public System.Threading.Tasks.Task<string> ModificarAulaAsync(RecursosHumanos.AulaService.Aula aula, RecursosHumanos.AulaService.Adminstrador administrador) {
            return base.Channel.ModificarAulaAsync(aula, administrador);
        }
        
        public string EliminarAula(int ID_Aula, RecursosHumanos.AulaService.Adminstrador administrador) {
            return base.Channel.EliminarAula(ID_Aula, administrador);
        }
        
        public System.Threading.Tasks.Task<string> EliminarAulaAsync(int ID_Aula, RecursosHumanos.AulaService.Adminstrador administrador) {
            return base.Channel.EliminarAulaAsync(ID_Aula, administrador);
        }
        
        public RecursosHumanos.AulaService.Aula[] TraerAulas(string filtro) {
            return base.Channel.TraerAulas(filtro);
        }
        
        public System.Threading.Tasks.Task<RecursosHumanos.AulaService.Aula[]> TraerAulasAsync(string filtro) {
            return base.Channel.TraerAulasAsync(filtro);
        }
        
        public RecursosHumanos.AulaService.Aula ObtenerAula(int ID_Aula) {
            return base.Channel.ObtenerAula(ID_Aula);
        }
        
        public System.Threading.Tasks.Task<RecursosHumanos.AulaService.Aula> ObtenerAulaAsync(int ID_Aula) {
            return base.Channel.ObtenerAulaAsync(ID_Aula);
        }
    }
}
