//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanos.UsuarioServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WsRecursosHumanos.Estructuras")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioServicio.IUsuarioServicio")]
    public interface IUsuarioServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/AgregarUsuario", ReplyAction="http://tempuri.org/IUsuarioServicio/AgregarUsuarioResponse")]
        string AgregarUsuario(RecursosHumanos.UsuarioServicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/AgregarUsuario", ReplyAction="http://tempuri.org/IUsuarioServicio/AgregarUsuarioResponse")]
        System.Threading.Tasks.Task<string> AgregarUsuarioAsync(RecursosHumanos.UsuarioServicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/EditarUsuario", ReplyAction="http://tempuri.org/IUsuarioServicio/EditarUsuarioResponse")]
        string EditarUsuario(RecursosHumanos.UsuarioServicio.Usuario usuario, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/EditarUsuario", ReplyAction="http://tempuri.org/IUsuarioServicio/EditarUsuarioResponse")]
        System.Threading.Tasks.Task<string> EditarUsuarioAsync(RecursosHumanos.UsuarioServicio.Usuario usuario, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarioServicio/EliminarUsuarioResponse")]
        string EliminarUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarioServicio/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<string> EliminarUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/TraerUsuarios", ReplyAction="http://tempuri.org/IUsuarioServicio/TraerUsuariosResponse")]
        RecursosHumanos.UsuarioServicio.Usuario[] TraerUsuarios(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/TraerUsuarios", ReplyAction="http://tempuri.org/IUsuarioServicio/TraerUsuariosResponse")]
        System.Threading.Tasks.Task<RecursosHumanos.UsuarioServicio.Usuario[]> TraerUsuariosAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarioServicio/ObtenerUsuarioResponse")]
        RecursosHumanos.UsuarioServicio.Usuario ObtenerUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarioServicio/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<RecursosHumanos.UsuarioServicio.Usuario> ObtenerUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/CambiarClave", ReplyAction="http://tempuri.org/IUsuarioServicio/CambiarClaveResponse")]
        void CambiarClave(int id, string clave, RecursosHumanos.UsuarioServicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/CambiarClave", ReplyAction="http://tempuri.org/IUsuarioServicio/CambiarClaveResponse")]
        System.Threading.Tasks.Task CambiarClaveAsync(int id, string clave, RecursosHumanos.UsuarioServicio.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/ValidarSession", ReplyAction="http://tempuri.org/IUsuarioServicio/ValidarSessionResponse")]
        bool ValidarSession(string nombre, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServicio/ValidarSession", ReplyAction="http://tempuri.org/IUsuarioServicio/ValidarSessionResponse")]
        System.Threading.Tasks.Task<bool> ValidarSessionAsync(string nombre, string clave);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServicioChannel : RecursosHumanos.UsuarioServicio.IUsuarioServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServicioClient : System.ServiceModel.ClientBase<RecursosHumanos.UsuarioServicio.IUsuarioServicio>, RecursosHumanos.UsuarioServicio.IUsuarioServicio {
        
        public UsuarioServicioClient() {
        }
        
        public UsuarioServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AgregarUsuario(RecursosHumanos.UsuarioServicio.Usuario usuario) {
            return base.Channel.AgregarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<string> AgregarUsuarioAsync(RecursosHumanos.UsuarioServicio.Usuario usuario) {
            return base.Channel.AgregarUsuarioAsync(usuario);
        }
        
        public string EditarUsuario(RecursosHumanos.UsuarioServicio.Usuario usuario, int id) {
            return base.Channel.EditarUsuario(usuario, id);
        }
        
        public System.Threading.Tasks.Task<string> EditarUsuarioAsync(RecursosHumanos.UsuarioServicio.Usuario usuario, int id) {
            return base.Channel.EditarUsuarioAsync(usuario, id);
        }
        
        public string EliminarUsuario(int id) {
            return base.Channel.EliminarUsuario(id);
        }
        
        public System.Threading.Tasks.Task<string> EliminarUsuarioAsync(int id) {
            return base.Channel.EliminarUsuarioAsync(id);
        }
        
        public RecursosHumanos.UsuarioServicio.Usuario[] TraerUsuarios(string filtro) {
            return base.Channel.TraerUsuarios(filtro);
        }
        
        public System.Threading.Tasks.Task<RecursosHumanos.UsuarioServicio.Usuario[]> TraerUsuariosAsync(string filtro) {
            return base.Channel.TraerUsuariosAsync(filtro);
        }
        
        public RecursosHumanos.UsuarioServicio.Usuario ObtenerUsuario(int id) {
            return base.Channel.ObtenerUsuario(id);
        }
        
        public System.Threading.Tasks.Task<RecursosHumanos.UsuarioServicio.Usuario> ObtenerUsuarioAsync(int id) {
            return base.Channel.ObtenerUsuarioAsync(id);
        }
        
        public void CambiarClave(int id, string clave, RecursosHumanos.UsuarioServicio.Usuario usuario) {
            base.Channel.CambiarClave(id, clave, usuario);
        }
        
        public System.Threading.Tasks.Task CambiarClaveAsync(int id, string clave, RecursosHumanos.UsuarioServicio.Usuario usuario) {
            return base.Channel.CambiarClaveAsync(id, clave, usuario);
        }
        
        public bool ValidarSession(string nombre, string clave) {
            return base.Channel.ValidarSession(nombre, clave);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarSessionAsync(string nombre, string clave) {
            return base.Channel.ValidarSessionAsync(nombre, clave);
        }
    }
}
