//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanos.Grupo_EstudianteService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grupo_Estudiante", Namespace="http://schemas.datacontract.org/2004/07/WebServiceProyectoUniversidad.Estructuras" +
        "")]
    [System.SerializableAttribute()]
    public partial class Grupo_Estudiante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_EstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int N_RegistroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Estudiante {
            get {
                return this.ID_EstudianteField;
            }
            set {
                if ((this.ID_EstudianteField.Equals(value) != true)) {
                    this.ID_EstudianteField = value;
                    this.RaisePropertyChanged("ID_Estudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Grupo {
            get {
                return this.ID_GrupoField;
            }
            set {
                if ((this.ID_GrupoField.Equals(value) != true)) {
                    this.ID_GrupoField = value;
                    this.RaisePropertyChanged("ID_Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int N_Registro {
            get {
                return this.N_RegistroField;
            }
            set {
                if ((this.N_RegistroField.Equals(value) != true)) {
                    this.N_RegistroField = value;
                    this.RaisePropertyChanged("N_Registro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adminstrador", Namespace="http://schemas.datacontract.org/2004/07/WebServiceProyectoUniversidad.Estructuras" +
        "")]
    [System.SerializableAttribute()]
    public partial class Adminstrador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grupo_Estudiantes", Namespace="http://schemas.datacontract.org/2004/07/WebServiceProyectoUniversidad.Estructuras" +
        "")]
    [System.SerializableAttribute()]
    public partial class Grupo_Estudiantes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_EstudianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((this.CedulaField.Equals(value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Estudiante {
            get {
                return this.ID_EstudianteField;
            }
            set {
                if ((this.ID_EstudianteField.Equals(value) != true)) {
                    this.ID_EstudianteField = value;
                    this.RaisePropertyChanged("ID_Estudiante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Grupo {
            get {
                return this.ID_GrupoField;
            }
            set {
                if ((this.ID_GrupoField.Equals(value) != true)) {
                    this.ID_GrupoField = value;
                    this.RaisePropertyChanged("ID_Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Grupo_EstudianteService.IGrupo_EstudianteService")]
    public interface IGrupo_EstudianteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupo_EstudianteService/InsertarRegistro", ReplyAction="http://tempuri.org/IGrupo_EstudianteService/InsertarRegistroResponse")]
        string InsertarRegistro(RecursosHumanos.Grupo_EstudianteService.Grupo_Estudiante grupo_estudiante, RecursosHumanos.Grupo_EstudianteService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupo_EstudianteService/InsertarRegistro", ReplyAction="http://tempuri.org/IGrupo_EstudianteService/InsertarRegistroResponse")]
        System.Threading.Tasks.Task<string> InsertarRegistroAsync(RecursosHumanos.Grupo_EstudianteService.Grupo_Estudiante grupo_estudiante, RecursosHumanos.Grupo_EstudianteService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupo_EstudianteService/ModificarRegistro", ReplyAction="http://tempuri.org/IGrupo_EstudianteService/ModificarRegistroResponse")]
        string ModificarRegistro(RecursosHumanos.Grupo_EstudianteService.Grupo_Estudiante grupo_estudiante, RecursosHumanos.Grupo_EstudianteService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupo_EstudianteService/ModificarRegistro", ReplyAction="http://tempuri.org/IGrupo_EstudianteService/ModificarRegistroResponse")]
        System.Threading.Tasks.Task<string> ModificarRegistroAsync(RecursosHumanos.Grupo_EstudianteService.Grupo_Estudiante grupo_estudiante, RecursosHumanos.Grupo_EstudianteService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupo_EstudianteService/EliminarRegistro", ReplyAction="http://tempuri.org/IGrupo_EstudianteService/EliminarRegistroResponse")]
        string EliminarRegistro(int n_registro, RecursosHumanos.Grupo_EstudianteService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupo_EstudianteService/EliminarRegistro", ReplyAction="http://tempuri.org/IGrupo_EstudianteService/EliminarRegistroResponse")]
        System.Threading.Tasks.Task<string> EliminarRegistroAsync(int n_registro, RecursosHumanos.Grupo_EstudianteService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupo_EstudianteService/EstudiantesGrupo", ReplyAction="http://tempuri.org/IGrupo_EstudianteService/EstudiantesGrupoResponse")]
        RecursosHumanos.Grupo_EstudianteService.Grupo_Estudiantes[] EstudiantesGrupo(int id_grupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupo_EstudianteService/EstudiantesGrupo", ReplyAction="http://tempuri.org/IGrupo_EstudianteService/EstudiantesGrupoResponse")]
        System.Threading.Tasks.Task<RecursosHumanos.Grupo_EstudianteService.Grupo_Estudiantes[]> EstudiantesGrupoAsync(int id_grupo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGrupo_EstudianteServiceChannel : RecursosHumanos.Grupo_EstudianteService.IGrupo_EstudianteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Grupo_EstudianteServiceClient : System.ServiceModel.ClientBase<RecursosHumanos.Grupo_EstudianteService.IGrupo_EstudianteService>, RecursosHumanos.Grupo_EstudianteService.IGrupo_EstudianteService {
        
        public Grupo_EstudianteServiceClient() {
        }
        
        public Grupo_EstudianteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Grupo_EstudianteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Grupo_EstudianteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Grupo_EstudianteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertarRegistro(RecursosHumanos.Grupo_EstudianteService.Grupo_Estudiante grupo_estudiante, RecursosHumanos.Grupo_EstudianteService.Adminstrador administrador) {
            return base.Channel.InsertarRegistro(grupo_estudiante, administrador);
        }
        
        public System.Threading.Tasks.Task<string> InsertarRegistroAsync(RecursosHumanos.Grupo_EstudianteService.Grupo_Estudiante grupo_estudiante, RecursosHumanos.Grupo_EstudianteService.Adminstrador administrador) {
            return base.Channel.InsertarRegistroAsync(grupo_estudiante, administrador);
        }
        
        public string ModificarRegistro(RecursosHumanos.Grupo_EstudianteService.Grupo_Estudiante grupo_estudiante, RecursosHumanos.Grupo_EstudianteService.Adminstrador administrador) {
            return base.Channel.ModificarRegistro(grupo_estudiante, administrador);
        }
        
        public System.Threading.Tasks.Task<string> ModificarRegistroAsync(RecursosHumanos.Grupo_EstudianteService.Grupo_Estudiante grupo_estudiante, RecursosHumanos.Grupo_EstudianteService.Adminstrador administrador) {
            return base.Channel.ModificarRegistroAsync(grupo_estudiante, administrador);
        }
        
        public string EliminarRegistro(int n_registro, RecursosHumanos.Grupo_EstudianteService.Adminstrador administrador) {
            return base.Channel.EliminarRegistro(n_registro, administrador);
        }
        
        public System.Threading.Tasks.Task<string> EliminarRegistroAsync(int n_registro, RecursosHumanos.Grupo_EstudianteService.Adminstrador administrador) {
            return base.Channel.EliminarRegistroAsync(n_registro, administrador);
        }
        
        public RecursosHumanos.Grupo_EstudianteService.Grupo_Estudiantes[] EstudiantesGrupo(int id_grupo) {
            return base.Channel.EstudiantesGrupo(id_grupo);
        }
        
        public System.Threading.Tasks.Task<RecursosHumanos.Grupo_EstudianteService.Grupo_Estudiantes[]> EstudiantesGrupoAsync(int id_grupo) {
            return base.Channel.EstudiantesGrupoAsync(id_grupo);
        }
    }
}
