//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanos.ProfesorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/WebServiceProyectoUniversidad.Estructuras" +
        "")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((this.CedulaField.Equals(value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profesor", Namespace="http://schemas.datacontract.org/2004/07/WebServiceProyectoUniversidad.Estructuras" +
        "")]
    [System.SerializableAttribute()]
    public partial class Profesor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_CarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ProfesroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Carrera {
            get {
                return this.ID_CarreraField;
            }
            set {
                if ((this.ID_CarreraField.Equals(value) != true)) {
                    this.ID_CarreraField = value;
                    this.RaisePropertyChanged("ID_Carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Profesro {
            get {
                return this.ID_ProfesroField;
            }
            set {
                if ((this.ID_ProfesroField.Equals(value) != true)) {
                    this.ID_ProfesroField = value;
                    this.RaisePropertyChanged("ID_Profesro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adminstrador", Namespace="http://schemas.datacontract.org/2004/07/WebServiceProyectoUniversidad.Estructuras" +
        "")]
    [System.SerializableAttribute()]
    public partial class Adminstrador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfesorPersona", Namespace="http://schemas.datacontract.org/2004/07/WebServiceProyectoUniversidad.Estructuras" +
        "")]
    [System.SerializableAttribute()]
    public partial class ProfesorPersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_CarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ProfesroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((this.CedulaField.Equals(value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Carrera {
            get {
                return this.ID_CarreraField;
            }
            set {
                if ((this.ID_CarreraField.Equals(value) != true)) {
                    this.ID_CarreraField = value;
                    this.RaisePropertyChanged("ID_Carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Profesro {
            get {
                return this.ID_ProfesroField;
            }
            set {
                if ((this.ID_ProfesroField.Equals(value) != true)) {
                    this.ID_ProfesroField = value;
                    this.RaisePropertyChanged("ID_Profesro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProfesorService.IProfesorService")]
    public interface IProfesorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfesorService/InsertarProfesor", ReplyAction="http://tempuri.org/IProfesorService/InsertarProfesorResponse")]
        string InsertarProfesor(RecursosHumanos.ProfesorService.Persona persona, RecursosHumanos.ProfesorService.Profesor Profesor, RecursosHumanos.ProfesorService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfesorService/InsertarProfesor", ReplyAction="http://tempuri.org/IProfesorService/InsertarProfesorResponse")]
        System.Threading.Tasks.Task<string> InsertarProfesorAsync(RecursosHumanos.ProfesorService.Persona persona, RecursosHumanos.ProfesorService.Profesor Profesor, RecursosHumanos.ProfesorService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfesorService/ModificarProfesor", ReplyAction="http://tempuri.org/IProfesorService/ModificarProfesorResponse")]
        string ModificarProfesor(RecursosHumanos.ProfesorService.Persona persona, RecursosHumanos.ProfesorService.Profesor Profesor, RecursosHumanos.ProfesorService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfesorService/ModificarProfesor", ReplyAction="http://tempuri.org/IProfesorService/ModificarProfesorResponse")]
        System.Threading.Tasks.Task<string> ModificarProfesorAsync(RecursosHumanos.ProfesorService.Persona persona, RecursosHumanos.ProfesorService.Profesor Profesor, RecursosHumanos.ProfesorService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfesorService/EliminarProfesor", ReplyAction="http://tempuri.org/IProfesorService/EliminarProfesorResponse")]
        string EliminarProfesor(int ID_Profesor, RecursosHumanos.ProfesorService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfesorService/EliminarProfesor", ReplyAction="http://tempuri.org/IProfesorService/EliminarProfesorResponse")]
        System.Threading.Tasks.Task<string> EliminarProfesorAsync(int ID_Profesor, RecursosHumanos.ProfesorService.Adminstrador administrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfesorService/TraerProfesores", ReplyAction="http://tempuri.org/IProfesorService/TraerProfesoresResponse")]
        RecursosHumanos.ProfesorService.ProfesorPersona[] TraerProfesores(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfesorService/TraerProfesores", ReplyAction="http://tempuri.org/IProfesorService/TraerProfesoresResponse")]
        System.Threading.Tasks.Task<RecursosHumanos.ProfesorService.ProfesorPersona[]> TraerProfesoresAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfesorService/ObtenerProfesor", ReplyAction="http://tempuri.org/IProfesorService/ObtenerProfesorResponse")]
        RecursosHumanos.ProfesorService.ProfesorPersona ObtenerProfesor(int ID_Profesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProfesorService/ObtenerProfesor", ReplyAction="http://tempuri.org/IProfesorService/ObtenerProfesorResponse")]
        System.Threading.Tasks.Task<RecursosHumanos.ProfesorService.ProfesorPersona> ObtenerProfesorAsync(int ID_Profesor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfesorServiceChannel : RecursosHumanos.ProfesorService.IProfesorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfesorServiceClient : System.ServiceModel.ClientBase<RecursosHumanos.ProfesorService.IProfesorService>, RecursosHumanos.ProfesorService.IProfesorService {
        
        public ProfesorServiceClient() {
        }
        
        public ProfesorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfesorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfesorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfesorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertarProfesor(RecursosHumanos.ProfesorService.Persona persona, RecursosHumanos.ProfesorService.Profesor Profesor, RecursosHumanos.ProfesorService.Adminstrador administrador) {
            return base.Channel.InsertarProfesor(persona, Profesor, administrador);
        }
        
        public System.Threading.Tasks.Task<string> InsertarProfesorAsync(RecursosHumanos.ProfesorService.Persona persona, RecursosHumanos.ProfesorService.Profesor Profesor, RecursosHumanos.ProfesorService.Adminstrador administrador) {
            return base.Channel.InsertarProfesorAsync(persona, Profesor, administrador);
        }
        
        public string ModificarProfesor(RecursosHumanos.ProfesorService.Persona persona, RecursosHumanos.ProfesorService.Profesor Profesor, RecursosHumanos.ProfesorService.Adminstrador administrador) {
            return base.Channel.ModificarProfesor(persona, Profesor, administrador);
        }
        
        public System.Threading.Tasks.Task<string> ModificarProfesorAsync(RecursosHumanos.ProfesorService.Persona persona, RecursosHumanos.ProfesorService.Profesor Profesor, RecursosHumanos.ProfesorService.Adminstrador administrador) {
            return base.Channel.ModificarProfesorAsync(persona, Profesor, administrador);
        }
        
        public string EliminarProfesor(int ID_Profesor, RecursosHumanos.ProfesorService.Adminstrador administrador) {
            return base.Channel.EliminarProfesor(ID_Profesor, administrador);
        }
        
        public System.Threading.Tasks.Task<string> EliminarProfesorAsync(int ID_Profesor, RecursosHumanos.ProfesorService.Adminstrador administrador) {
            return base.Channel.EliminarProfesorAsync(ID_Profesor, administrador);
        }
        
        public RecursosHumanos.ProfesorService.ProfesorPersona[] TraerProfesores(string filtro) {
            return base.Channel.TraerProfesores(filtro);
        }
        
        public System.Threading.Tasks.Task<RecursosHumanos.ProfesorService.ProfesorPersona[]> TraerProfesoresAsync(string filtro) {
            return base.Channel.TraerProfesoresAsync(filtro);
        }
        
        public RecursosHumanos.ProfesorService.ProfesorPersona ObtenerProfesor(int ID_Profesor) {
            return base.Channel.ObtenerProfesor(ID_Profesor);
        }
        
        public System.Threading.Tasks.Task<RecursosHumanos.ProfesorService.ProfesorPersona> ObtenerProfesorAsync(int ID_Profesor) {
            return base.Channel.ObtenerProfesorAsync(ID_Profesor);
        }
    }
}
