//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34011
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsRecursosHumanos.IndicadoresEconomicos {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.sdde.bccr.fi.cr", ConfigurationName="IndicadoresEconomicos.wsIndicadoresEconomicosSoap")]
    public interface wsIndicadoresEconomicosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerIndicadoresEconomicos(string tcIndicador, string tcFechaInicio, string tcFechaFinal, string tcNombre, string tnSubNiveles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerIndicadoresEconomicosAsync(string tcIndicador, string tcFechaInicio, string tcFechaFinal, string tcNombre, string tnSubNiveles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicosXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ObtenerIndicadoresEconomicosXML(string tcIndicador, string tcFechaInicio, string tcFechaFinal, string tcNombre, string tnSubNiveles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicosXML", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ObtenerIndicadoresEconomicosXMLAsync(string tcIndicador, string tcFechaInicio, string tcFechaFinal, string tcNombre, string tnSubNiveles);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsIndicadoresEconomicosSoapChannel : WsRecursosHumanos.IndicadoresEconomicos.wsIndicadoresEconomicosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsIndicadoresEconomicosSoapClient : System.ServiceModel.ClientBase<WsRecursosHumanos.IndicadoresEconomicos.wsIndicadoresEconomicosSoap>, WsRecursosHumanos.IndicadoresEconomicos.wsIndicadoresEconomicosSoap {
        
        public wsIndicadoresEconomicosSoapClient() {
        }
        
        public wsIndicadoresEconomicosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsIndicadoresEconomicosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsIndicadoresEconomicosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsIndicadoresEconomicosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ObtenerIndicadoresEconomicos(string tcIndicador, string tcFechaInicio, string tcFechaFinal, string tcNombre, string tnSubNiveles) {
            return base.Channel.ObtenerIndicadoresEconomicos(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerIndicadoresEconomicosAsync(string tcIndicador, string tcFechaInicio, string tcFechaFinal, string tcNombre, string tnSubNiveles) {
            return base.Channel.ObtenerIndicadoresEconomicosAsync(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles);
        }
        
        public string ObtenerIndicadoresEconomicosXML(string tcIndicador, string tcFechaInicio, string tcFechaFinal, string tcNombre, string tnSubNiveles) {
            return base.Channel.ObtenerIndicadoresEconomicosXML(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerIndicadoresEconomicosXMLAsync(string tcIndicador, string tcFechaInicio, string tcFechaFinal, string tcNombre, string tnSubNiveles) {
            return base.Channel.ObtenerIndicadoresEconomicosXMLAsync(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles);
        }
    }
}
